### ISSUE TITLE
Evaluation of Your Computer-Controlled Cutting Assignment

### ISSUE THREAD

**Issue by BehnazNorouzi** [diepnguyenhoang/fablab_projectmanagementhub#1]
Hi Diep :)

Such a thorough documentation indeed. I enjoyed reading about your work and I should say that you've done a very good job and got beautiful results :) Your documentation is one of the rare ones without typo! Thanks for your effort in preparing a good documentation.

**Little things to fix**:

1. ~For setting the vinyl cutter for my image, I chose Edge >> Here, you can mention that the width of the material was measured and shown on the display when you chose edge.~
2. ~JOG: (or the Origin) >> Jog is not origin so you cannot say 'or the origin'. With jog you set the origin.~
3. ~Remember that after each adjustment, we need to press the joystick so that the system can save our setting. >> This is true for after jog and focus adjustment. But, after choosing job, you don't need to press the joystick, you just need to press the go button to start the job.~
4. ~and made use of the digital calculator >> the name of the tool is 'caliper'.~
5. ~Please add .stl file of your 3D press-fit design; .stl is a global format and enables people who do not have Fusion 360 installed to see your file using other software that they have.~

**Other comments for you**:
- For vinyl cutting, the line width does not necessarily need to be 0.02 mm. If you remember, we tested vinyl cutting with different line widths and it did not affect the result at all because the depth of cutting in vinyl cutting can be affected by factors such as the knife width itself as well as the pen force.
- - That is true about what happened to your butterfly. You have too many details and their lines are very close to each other without enough gap for the knife to freely move and cut them without interfering with the other lines which are close by. You can see about the blade design [here](https://www.lamtekno.fi/files/products/Cutter_Blade_Reference_Guide.pdf). So, if in your design, you consider a bigger line width, for example 1 mm or so, then you will see that the butterfly lines close to each other will overlap somehow so I recommend to consider a bigger line width; although it will not affect the result, it will help you to estimate the shape of the cut after vinyl cutting. In the following picture, your butterfly with 0.02 mm line width is at the left and I made the line width 1 mm for the butterfly in the right; now you can compare better :)
   - ![Butterfly-BigLineWidth](https://user-images.githubusercontent.com/14317529/152298144-4d4f8f57-321d-47fb-b6b3-22e2ff659796.jpg)
- Very good use of Fusion 360 for the first time :)
- Design steps are well described.
- I need and it is time for assemblingggg >> Happy assembling time indeed, I can see it from your text :)
- The size of the pictures are just good and small though the quality of the pictures is good. Can you tell me how you did it? Did you use any tool for that?

**Next step**:
Please let me know when you do those little fixations that I have suggested above (1-5). You can write under this issue a comment when you fix things.

Bests,
Behnaz

**Comment by diepnguyenhoang** [comment]
Hi Behnaz,
Thank you so much for the evaluating my assignment thoroughtly.
I have added and corrected as suggested. Kindly check it.
Also thank you for the clarification on the line width of the butterfly, I will drop by fablab and try to test it with 1mm to see the difference.
For the size of the pictures, if you mean the pictures I used in the web page to illustrate, I actually use FastStone Photo Resizer software to resize and choose the 640x480 size. 

Regards,
Diep

**Comment by BehnazNorouzi** [comment]
Hi Diep,

Thanks for your quick fixation and response.

Everything looks good; And your computer-controlled cutting week is passed from my point of view. Therefore, I close this issue.

Please note that, actually the point that I made was that if you set the line width to 1 mm even, the actual result after vinyl cutting will not change. But you can see from the design that your lines will overlap.
But maybe if you make the size of the butterfly bigger, then the problem will be solved.

Bests,
Behnaz
